### ISSUE TITLE
Persistence not being able to fetch UMA token

### ISSUE THREAD

**Issue by christian-hawk** [GluuFederation/inbound-saml#121]
**Describe the bug**
Even with module-exclusive tests working, persistence is not being able to fetch UMA token from oxAuth endpoint when testing with an online gluu-server instance.

**Expected behavior**
Retrieve bearer token for further operations. oxAuth logs should look like this: 
```
2022-03-23 15:20:30,848 INFO  [ForkJoinPool.commonPool-worker-5] [org.gluu.service.logger.LoggerService] (LoggerService.java:205) - Updated log level of '123' loggers to DEBUG
2022-03-23 15:20:37,379 DEBUG [qtp1831477404-16] [org.gluu.oxauth.service.ClientService] (ClientService.java:133) - Found 1 entries for client id = 1402.f5be51f3-e576-44c0-9763-f99340a6b178
2022-03-23 15:20:37,379 DEBUG [qtp1831477404-16] [org.gluu.oxauth.service.ClientService] (ClientService.java:133) - Found 1 entries for client id = 1402.f5be51f3-e576-44c0-9763-f99340a6b178
2022-03-23 15:20:37,379 DEBUG [qtp1831477404-16] [org.gluu.oxauth.auth.AuthenticationFilter] (AuthenticationFilter.java:142) - Starting endpoint authentication https://apitest.techno24x7.com/oxauth/restv1/token
2022-03-23 15:20:37,379 DEBUG [qtp1831477404-16] [org.gluu.oxauth.auth.AuthenticationFilter] (AuthenticationFilter.java:154) - Starting JWT token endpoint authentication
2022-03-23 15:20:37,380 DEBUG [qtp1831477404-16] [org.gluu.oxauth.service.ClientService] (ClientService.java:133) - Found 1 entries for client id = 1402.f5be51f3-e576-44c0-9763-f99340a6b178
2022-03-23 15:20:37,382 DEBUG [qtp1831477404-16] [org.gluu.oxauth.service.AuthenticationService] (AuthenticationService.java:686) - ConfigureSessionClient: username: '1402.f5be51f3-e576-44c0-9763-f99340a6b178', credentials: '1566951244'
2022-03-23 15:20:37,382 DEBUG [qtp1831477404-16] [org.gluu.oxauth.service.ClientService] (ClientService.java:133) - Found 1 entries for client id = 1402.f5be51f3-e576-44c0-9763-f99340a6b178
2022-03-23 15:20:37,383 INFO  [qtp1831477404-16] [org.gluu.oxauth.auth.Authenticator] (Authenticator.java:278) - Authentication success for Client: '1402.f5be51f3-e576-44c0-9763-f99340a6b178'
2022-03-23 15:20:37,384 DEBUG [qtp1831477404-16] [gluu.oxauth.token.ws.rs.TokenRestWebServiceImpl] (TokenRestWebServiceImpl.java:124) - Attempting to request access token: grantType = urn:ietf:params:oauth:grant-type:uma-ticket, code = null, redirectUri = null, username = null, refreshToken = null, clientId = 1402.f5be51f3-e576-44c0-9763-f99340a6b178, ExtraParams = {client_assertion_type=[urn:ietf:params:oauth:client-assertion-type:jwt-bearer], ticket=[09f8e833-9e55-4712-9e17-6b08562ee6ce], grant_type=[urn:ietf:params:oauth:grant-type:uma-ticket], scope=[oxtrust-api-read oxtrust-api-write], client_assertion=[eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjYwMWQwNmE1LTI5ODEtNGM2Yy05NjczLWEyNjI4OTQ3ZWZhZV9zaWdfcnMyNTYifQ.eyJpc3MiOiIxNDAyLmY1YmU1MWYzLWU1NzYtNDRjMC05NzYzLWY5OTM0MGE2YjE3OCIsInN1YiI6IjE0MDIuZjViZTUxZjMtZTU3Ni00NGMwLTk3NjMtZjk5MzQwYTZiMTc4IiwiaWF0IjoxNjQ0ODUwNjMzLCJleHAiOjE2NTQ4OTAyMzMsImp0aSI6IjlmZjRlZGZlLWQyOGItNGNhZC04ZGM2LTliNjMzODBjODQyMyIsImF1ZCI6Imh0dHBzOi8vYXBpdGVzdC50ZWNobm8yNHg3LmNvbS9veGF1dGgvcmVzdHYxL3Rva2VuIn0.TKC24FHpIGJ3xlYH1dCPlFRLsy1yRYywf9gP8Ow8ueg6Vl6U-KKigVVVj8egD213aXqdOw3gfvcFBr4ZYXY_VzBVioRPF91-m81Ib7YzLxBOOMaf4rKj_rutbhP1WcVLfdwF_u6W68_tF0vSei6Xbc2px__h1hINd4blFHVlScs-HnZ1UOLPCwCYHZc000X9olpGJGJbHFLBuiHSKB00ROAUktttaBQA2Mm0llws0OAzLZ5-Kgq9V4I3Wx905ZHv9Gcx8A17nDyIl4V2K5tKZ3406G-yZqnTUAhtYo0XwxXzULFvuPMqj6KPa1uLUGkrIaO1DmzYDn_TJZWCNavdeQ], client_id=[1402.f5be51f3-e576-44c0-9763-f99340a6b178]}, isSecure = true, codeVerifier = null, ticket = 09f8e833-9e55-4712-9e17-6b08562ee6ce
2022-03-23 15:20:37,443 DEBUG [qtp1831477404-16] [org.gluu.oxauth.service.external.ExternalUmaRptPolicyService] (ExternalUmaRptPolicyService.java:105) - Executing python 'getRequiredClaims' method, script: oxtrust_api_access_policy
2022-03-23 15:20:37,455 DEBUG [qtp1831477404-16] [org.gluu.oxauth.service.external.ExternalUmaRptPolicyService] (ExternalUmaRptPolicyService.java:107) - python 'getRequiredClaims' result: []
2022-03-23 15:20:37,455 DEBUG [qtp1831477404-16] [org.gluu.oxauth.service.external.ExternalUmaRptPolicyService] (ExternalUmaRptPolicyService.java:118) - Executing python 'getClaimsGatheringScriptName' method, script: oxtrust_api_access_policy
2022-03-23 15:20:37,455 DEBUG [qtp1831477404-16] [org.gluu.oxauth.service.external.ExternalUmaRptPolicyService] (ExternalUmaRptPolicyService.java:120) - python 'getClaimsGatheringScriptName' result: no_script
2022-03-23 15:20:37,460 DEBUG [qtp1831477404-16] [org.gluu.oxauth.service.external.ExternalUmaRptPolicyService] (ExternalUmaRptPolicyService.java:92) - Executing python 'authorize' method, script: oxtrust_api_access_policy
2022-03-23 15:20:37,467 DEBUG [qtp1831477404-16] [org.gluu.oxauth.service.external.ExternalUmaRptPolicyService] (ExternalUmaRptPolicyService.java:94) - python 'authorize' result: true
``` 

**Actual behavior**
oxauth logs:
```
2022-03-23 15:59:30,954 DEBUG [qtp1831477404-22] [org.gluu.oxauth.service.ClientService] (ClientService.java:133) - Found 1 entries for client id = 1402.f5be51f3-e576-44c0-9763-f99340a6b178
2022-03-23 15:59:30,954 DEBUG [qtp1831477404-22] [org.gluu.oxauth.service.ClientService] (ClientService.java:133) - Found 1 entries for client id = 1402.f5be51f3-e576-44c0-9763-f99340a6b178
2022-03-23 15:59:30,954 DEBUG [qtp1831477404-22] [org.gluu.oxauth.auth.AuthenticationFilter] (AuthenticationFilter.java:142) - Starting endpoint authentication https://apitest.techno24x7.com/oxauth/restv1/token
2022-03-23 15:59:30,954 DEBUG [qtp1831477404-22] [org.gluu.oxauth.auth.AuthenticationFilter] (AuthenticationFilter.java:154) - Starting JWT token endpoint authentication
2022-03-23 15:59:30,955 DEBUG [qtp1831477404-22] [org.gluu.oxauth.service.ClientService] (ClientService.java:133) - Found 1 entries for client id = 1402.f5be51f3-e576-44c0-9763-f99340a6b178
2022-03-23 15:59:30,956 INFO  [qtp1831477404-22] [org.gluu.oxauth.auth.AuthenticationFilter] (AuthenticationFilter.java:473) - JWT authentication failed: {}
org.gluu.oxauth.model.exception.InvalidJwtException: Cannot verify the JWT
	at org.gluu.oxauth.model.token.ClientAssertion.<init>(ClientAssertion.java:49) ~[classes/:?]
	at org.gluu.oxauth.auth.AuthenticationFilter.processJwtAuth(AuthenticationFilter.java:453) ~[classes/:?]
	at org.gluu.oxauth.auth.AuthenticationFilter.doFilter(AuthenticationFilter.java:155) ~[classes/:?]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.gluu.server.filters.AbstractCorsFilter.handleNonCORS(AbstractCorsFilter.java:362) ~[oxcore-server-4.3.1.Final.jar:?]
	at org.gluu.server.filters.AbstractCorsFilter.doFilter(AbstractCorsFilter.java:139) ~[oxcore-server-4.3.1.Final.jar:?]
	at org.gluu.oxauth.filter.CorsFilter.doFilter(CorsFilter.java:118) ~[classes/:?]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548) ~[jetty-servlet-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:600) ~[jetty-security-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501) ~[jetty-servlet-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:234) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.Server.handle(Server.java:516) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:400) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:645) [jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:392) [jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277) [jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [jetty-io-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) [jetty-io-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) [jetty-io-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338) [jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315) [jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173) [jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131) [jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409) [jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883) [jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034) [jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: org.gluu.oxauth.model.exception.InvalidJwtException: Invalid cryptographic segment
	at org.gluu.oxauth.model.token.ClientAssertion.load(ClientAssertion.java:119) ~[classes/:?]
	at org.gluu.oxauth.model.token.ClientAssertion.<init>(ClientAssertion.java:43) ~[classes/:?]
	... 42 more
2022-03-23 15:59:30,957 DEBUG [qtp1831477404-22] [org.gluu.oxauth.model.error.ErrorResponseFactory] (ErrorResponseFactory.java:72) - Looking for the error with id: invalid_client
2022-03-23 15:59:30,957 DEBUG [qtp1831477404-22] [org.gluu.oxauth.model.error.ErrorResponseFactory] (ErrorResponseFactory.java:77) - Found error, id: invalid_client
2022-03-23 15:59:31,542 DEBUG [qtp1831477404-16] [org.gluu.oxauth.service.common.UserService] (UserService.java:81) - Getting user information from LDAP: userId = null
2022-03-23 15:59:31,542 DEBUG [qtp1831477404-16] [org.gluu.oxauth.service.ClientService] (ClientService.java:133) - Found 1 entries for client id = 1401.add8dc7c-0b82-4fa1-9865-9a741e03ad6d
2022-03-23 15:59:31,544 ERROR [qtp1831477404-16] [org.gluu.oxauth.uma.service.UmaRptService] (UmaRptService.java:121) - Failed to find entry: tknCde=eb045d78d273107348b0300c01d29b7552d622abbc6faf81b3ec55359aa9950c,ou=uma_rpt,ou=tokens,o=gluu
org.gluu.persist.exception.EntryPersistenceException: Failed to find entry: tknCde=eb045d78d273107348b0300c01d29b7552d622abbc6faf81b3ec55359aa9950c,ou=uma_rpt,ou=tokens,o=gluu
	at org.gluu.persist.ldap.impl.LdapEntryManager.find(LdapEntryManager.java:405) ~[gluu-orm-ldap-4.3.1.Final.jar:?]
	at org.gluu.persist.impl.BaseEntryManager.find(BaseEntryManager.java:713) ~[gluu-orm-core-4.3.1.Final.jar:?]
	at org.gluu.persist.impl.BaseEntryManager.find(BaseEntryManager.java:592) ~[gluu-orm-core-4.3.1.Final.jar:?]
	at org.gluu.persist.impl.BaseEntryManager.find(BaseEntryManager.java:579) ~[gluu-orm-core-4.3.1.Final.jar:?]
	at jdk.internal.reflect.GeneratedMethodAccessor92.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38) ~[weld-core-impl-3.1.8.Final.jar:3.1.8.Final]
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:106) ~[weld-core-impl-3.1.8.Final.jar:3.1.8.Final]
	at org.gluu.persist.PersistenceEntryManager$EntityManager$1948487569$Proxy$_$$_WeldClientProxy.find(Unknown Source) ~[gluu-orm-core-4.3.1.Final.jar:?]
	at org.gluu.oxauth.uma.service.UmaRptService.getRPTByCode(UmaRptService.java:114) ~[classes/:?]
	at org.gluu.oxauth.uma.service.UmaRptService$Proxy$_$$_WeldClientProxy.getRPTByCode(Unknown Source) ~[classes/:?]
	at org.gluu.oxauth.uma.ws.rs.UmaRptIntrospectionWS.introspect(UmaRptIntrospectionWS.java:89) ~[classes/:?]
	at org.gluu.oxauth.uma.ws.rs.UmaRptIntrospectionWS.introspectPost(UmaRptIntrospectionWS.java:82) ~[classes/:?]
	at org.gluu.oxauth.uma.ws.rs.UmaRptIntrospectionWS$Proxy$_$$_WeldClientProxy.introspectPost(Unknown Source) ~[classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170) ~[resteasy-core-4.5.7.Final.jar:4.5.7.Final]
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130) ~[resteasy-core-4.5.7.Final.jar:4.5.7.Final]
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:643) ~[resteasy-core-4.5.7.Final.jar:4.5.7.Final]
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:507) ~[resteasy-core-4.5.7.Final.jar:4.5.7.Final]
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:457) ~[resteasy-core-4.5.7.Final.jar:4.5.7.Final]
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364) ~[resteasy-core-4.5.7.Final.jar:4.5.7.Final]
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:459) ~[resteasy-core-4.5.7.Final.jar:4.5.7.Final]
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:419) ~[resteasy-core-4.5.7.Final.jar:4.5.7.Final]
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:393) ~[resteasy-core-4.5.7.Final.jar:4.5.7.Final]
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:68) ~[resteasy-core-4.5.7.Final.jar:4.5.7.Final]
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492) ~[resteasy-core-4.5.7.Final.jar:4.5.7.Final]
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261) ~[resteasy-core-4.5.7.Final.jar:4.5.7.Final]
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161) ~[resteasy-core-4.5.7.Final.jar:4.5.7.Final]
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364) ~[resteasy-core-4.5.7.Final.jar:4.5.7.Final]
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164) ~[resteasy-core-4.5.7.Final.jar:4.5.7.Final]
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247) ~[resteasy-core-4.5.7.Final.jar:4.5.7.Final]
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:249) ~[resteasy-core-4.5.7.Final.jar:4.5.7.Final]
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:60) ~[resteasy-core-4.5.7.Final.jar:4.5.7.Final]
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:55) ~[resteasy-core-4.5.7.Final.jar:4.5.7.Final]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) ~[servlet-api-3.1.jar:3.1.0]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799) ~[jetty-servlet-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1631) ~[jetty-servlet-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:228) ~[websocket-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.gluu.oxauth.audit.debug.ServletLoggingFilter.doFilter(ServletLoggingFilter.java:67) ~[classes/:?]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:201) ~[jetty-servlet-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.gluu.server.filters.AbstractCorsFilter.handleNonCORS(AbstractCorsFilter.java:362) ~[oxcore-server-4.3.1.Final.jar:?]
	at org.gluu.server.filters.AbstractCorsFilter.doFilter(AbstractCorsFilter.java:139) ~[oxcore-server-4.3.1.Final.jar:?]
	at org.gluu.oxauth.filter.CorsFilter.doFilter(CorsFilter.java:118) ~[classes/:?]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548) ~[jetty-servlet-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:600) ~[jetty-security-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501) ~[jetty-servlet-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:234) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.Server.handle(Server.java:516) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:400) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:645) [jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:392) [jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277) [jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [jetty-io-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) [jetty-io-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) [jetty-io-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338) [jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315) [jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173) [jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131) [jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409) [jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883) [jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034) [jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: org.gluu.persist.exception.operation.SearchException: Failed to lookup entry by DN: 'tknCde=eb045d78d273107348b0300c01d29b7552d622abbc6faf81b3ec55359aa9950c,ou=uma_rpt,ou=tokens,o=gluu'
	at org.gluu.persist.ldap.operation.impl.LdapOperationServiceImpl.lookupImpl(LdapOperationServiceImpl.java:629) ~[gluu-orm-ldap-4.3.1.Final.jar:?]
	at org.gluu.persist.ldap.operation.impl.LdapOperationServiceImpl.lookup(LdapOperationServiceImpl.java:605) ~[gluu-orm-ldap-4.3.1.Final.jar:?]
	at org.gluu.persist.ldap.impl.LdapEntryManager.find(LdapEntryManager.java:399) ~[gluu-orm-ldap-4.3.1.Final.jar:?]
	... 84 more
```

It looks like a problem with jwt encoding.

**Comment by christian-hawk** [comment]
closed by #122
